options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Step 1: Authenticate with Docker Hub
  - name: 'gcr.io/cloud-builders/docker'
    args: ['login', '-u', 'sultanulkabir', '-p', '']

  # Step 2: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'docker.io/sultanulkabir/flask-app:latest', '.']

  # Step 3: Push the Docker image to Docker Hub
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'docker.io/sultanulkabir/flask-app:latest']

  # Step 4: Update the GCP Compute Engine instance with the new container image
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['compute', 'instances', 'update-container', 'flask-instance', 
           '--zone=us-central1-c', '--container-image', 'docker.io/sultanulkabir/flask-app:latest']

timeout: '1200s'
